apiVersion: v1
kind: Service
metadata:
  name: httpd-service-nautilus
spec:
  type: NodePort
  selector:
    app: httpd_app_nautilus
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30004
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment-nautilus
  labels:
    app: httpd_app_nautilus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd_app_nautilus
  template:
    metadata:
      labels:
        app: httpd_app_nautilus
    spec:
      containers:
        - name: httpd-container-nautilus
          image: jenkins/jenkins:latest
          ports:
            - containerPort: 8080
